// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA-mX6gVchO2YWxgNnsDNrQrpiXThNLsc',
    appId: '1:951973497159:web:576dc90c8c20d2e197e462',
    messagingSenderId: '951973497159',
    projectId: 'sakani-c5cef',
    authDomain: 'sakani-c5cef.firebaseapp.com',
    storageBucket: 'sakani-c5cef.appspot.com',
    measurementId: 'G-B5YQ2CQNJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4DUy-ZoQefulX1oE5Z3wH0yVkGP8wuvs',
    appId: '1:951973497159:android:68d435f87387a8ea97e462',
    messagingSenderId: '951973497159',
    projectId: 'sakani-c5cef',
    storageBucket: 'sakani-c5cef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzNBDsUljyWfRJWG9A1vltm70pfDZCKPE',
    appId: '1:951973497159:ios:ea8a329f49c9edfc97e462',
    messagingSenderId: '951973497159',
    projectId: 'sakani-c5cef',
    storageBucket: 'sakani-c5cef.appspot.com',
    iosClientId:
        '951973497159-244kiu6i3hl9lj1a537830de07pjogtg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sakani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzNBDsUljyWfRJWG9A1vltm70pfDZCKPE',
    appId: '1:951973497159:ios:d557ec4750985da897e462',
    messagingSenderId: '951973497159',
    projectId: 'sakani-c5cef',
    storageBucket: 'sakani-c5cef.appspot.com',
    iosClientId:
        '951973497159-prqg0laurk20bqlgp99c7k1plspt2io4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sakani.RunnerTests',
  );
}
